@echo off
chcp 1251

SET server=localhost
SET database=postgres
SET port=5432
SET username=postgres

SET command1="create database socnetworkdbtest;"
SET command2="\c socnetworkdbtest;"
SET command3="CREATE TABLE Users (Id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, Name varchar(30), Age integer, Friends integer[]);"

"C:\Program Files\PostgreSQL\15\bin\psql.exe" -h %server% -U %username% -d %database% -p %port% -c %command1% -c %command2%  -c %command3%

pause